version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001-5003:5000'  # Map container port for the  replicas
      
    volumes:
      - todo_data:/app/todo_data
    deploy:
      replicas: 3

volumes:
  todo_data:
 
# A persistant storage paired with a dedicated volume is assigned so that app is restarted without the loss of data even when container is stopped.
# You can replicate this container or spawn multiple instances and still expect the same results.
